/*
    studio.h
    Generated by FMOD Designer v4.44.8 
*/

#ifndef STUDIO_H
#define STUDIO_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_STUDIO = 3;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_STUDIO_MAIN = 0;
const int EVENTGROUPCOUNT_STUDIO_MAIN = 3;
const int EVENT_STUDIO_MAIN_STORMLOOPEVENT = 0;
const int EVENT_STUDIO_MAIN_CRICKETSLOOPEVENT = 1;
const int EVENT_STUDIO_MAIN_HOPEVENT = 2;

/*
    Project-unique event ids
*/
const int EVENTID_STUDIO_MAIN_STORMLOOPEVENT = 0;
const int EVENTID_STUDIO_MAIN_CRICKETSLOOPEVENT = 1;
const int EVENTID_STUDIO_MAIN_HOPEVENT = 2;

const int EVENTCATEGORY_STUDIO_MASTER = 0;
const int EVENTCATEGORYCOUNT_STUDIO_MASTER = 3;

const int EVENTCATEGORY_STUDIO_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_STUDIO_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_STUDIO_MAIN_STORMLOOPEVENT = "{d4ec9768-8d4c-427c-9057-924b4e72db0c}";
const char *EVENTGUID_STUDIO_MAIN_CRICKETSLOOPEVENT = "{6af555f1-5a57-490b-aa3d-af54f508f6d3}";
const char *EVENTGUID_STUDIO_MAIN_HOPEVENT = "{3d3d281f-1331-4dc7-a8d9-f2d47a7b539c}";

#endif /* STUDIO_H */
