/*
    studio.h
    Generated by FMOD Designer v4.44.8 
*/

#ifndef STUDIO_H
#define STUDIO_H

/*
    Total number of events in the project
*/
const int EVENTCOUNT_STUDIO = 3;

/*
    EventGroup/Event-relative indices
*/
const int EVENTGROUP_STUDIO_MAIN = 0;
const int EVENTGROUPCOUNT_STUDIO_MAIN = 3;
const int EVENT_STUDIO_MAIN_LOOPCRICKETSEVENT = 0;
const int EVENT_STUDIO_MAIN_LOOPSTORMEVENT = 1;
const int EVENT_STUDIO_MAIN_PLAYHOPEVENT = 2;
const int EVENTPARAMETER_STUDIO_MAIN_PLAYHOPEVENT_PARAM00 = 0;

/*
    Project-unique event ids
*/
const int EVENTID_STUDIO_MAIN_LOOPCRICKETSEVENT = 0;
const int EVENTID_STUDIO_MAIN_LOOPSTORMEVENT = 1;
const int EVENTID_STUDIO_MAIN_PLAYHOPEVENT = 2;

const int EVENTCATEGORY_STUDIO_MASTER = 0;
const int EVENTCATEGORYCOUNT_STUDIO_MASTER = 3;

const int EVENTCATEGORY_STUDIO_MASTER_MUSIC = 0;
const int EVENTCATEGORYCOUNT_STUDIO_MASTER_MUSIC = 0;


/*
    Event GUIDs
*/
const char *EVENTGUID_STUDIO_MAIN_LOOPCRICKETSEVENT = "{8ac16708-5621-41b7-8731-0d9cb19dc5cf}";
const char *EVENTGUID_STUDIO_MAIN_LOOPSTORMEVENT = "{26f66d71-b73e-4a90-969c-2a56f11e3d19}";
const char *EVENTGUID_STUDIO_MAIN_PLAYHOPEVENT = "{f053a778-efa7-416e-8582-0c3e9aba56f7}";

#endif /* STUDIO_H */
